"""
Feast Feature Definitions — Industrial Intelligence Platform

Entities:
  - supply_chain_item: (item_id, store_id) composite key

Feature Views:
  - supply_chain_lag_features     — lag_7, lag_14, lag_28
  - supply_chain_rolling_features — rolling mean/std/max
  - supply_chain_price_features   — sell_price, price_rel_mean, price_change
  - supply_chain_calendar_features— dayofweek, month, is_weekend, holidays
  - supply_chain_category_features— dept/store/cat aggregations

On-demand Feature View:
  - supply_chain_demand_score     — composite signal derived at request time
"""

from datetime import timedelta

import pandas as pd
from feast import (
    Entity,
    Feature,
    FeatureView,
    Field,
    FileSource,
    OnDemandFeatureView,
    RequestSource,
    ValueType,
)
from feast.types import Float32, Float64, Int32, Int64, String


# ENTITIES


supply_chain_item = Entity(
    name="supply_chain_item",
    description="Unique item-store combination for supply chain forecasting",
    value_type=ValueType.STRING,
)


# DATA SOURCES (Parquet files generated by feature_engineering.py)


supply_chain_source = FileSource(
    name="supply_chain_features_source",
    path="feature_store/data/supply_chain_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)


# FEATURE VIEWS
supply_chain_lag_fv = FeatureView(
    name="supply_chain_lag_features",
    entities=[supply_chain_item],
    ttl=timedelta(days=35),
    schema=[
        Field(name="lag_7",  dtype=Float32),
        Field(name="lag_14", dtype=Float32),
        Field(name="lag_28", dtype=Float32),
    ],
    online=True,
    source=supply_chain_source,
    tags={"domain": "supply_chain", "type": "lag"},
)

supply_chain_rolling_fv = FeatureView(
    name="supply_chain_rolling_features",
    entities=[supply_chain_item],
    ttl=timedelta(days=35),
    schema=[
        Field(name="rolling_mean_7",  dtype=Float32),
        Field(name="rolling_std_7",   dtype=Float32),
        Field(name="rolling_max_7",   dtype=Float32),
        Field(name="rolling_mean_14", dtype=Float32),
        Field(name="rolling_std_14",  dtype=Float32),
        Field(name="rolling_max_14",  dtype=Float32),
        Field(name="rolling_mean_28", dtype=Float32),
        Field(name="rolling_std_28",  dtype=Float32),
        Field(name="rolling_max_28",  dtype=Float32),
    ],
    online=True,
    source=supply_chain_source,
    tags={"domain": "supply_chain", "type": "rolling"},
)

supply_chain_price_fv = FeatureView(
    name="supply_chain_price_features",
    entities=[supply_chain_item],
    ttl=timedelta(days=35),
    schema=[
        Field(name="sell_price",     dtype=Float32),
        Field(name="price_rel_mean", dtype=Float32),
        Field(name="price_change",   dtype=Float32),
    ],
    online=True,
    source=supply_chain_source,
    tags={"domain": "supply_chain", "type": "price"},
)

supply_chain_calendar_fv = FeatureView(
    name="supply_chain_calendar_features",
    entities=[supply_chain_item],
    ttl=timedelta(days=2),
    schema=[
        Field(name="dayofweek",         dtype=Int32),
        Field(name="dayofmonth",        dtype=Int32),
        Field(name="weekofyear",        dtype=Int32),
        Field(name="month",             dtype=Int32),
        Field(name="is_weekend",        dtype=Int32),
        Field(name="is_month_start",    dtype=Int32),
        Field(name="is_month_end",      dtype=Int32),
        Field(name="is_german_holiday", dtype=Int32),
        Field(name="has_event",         dtype=Int32),
    ],
    online=True,
    source=supply_chain_source,
    tags={"domain": "supply_chain", "type": "calendar"},
)

supply_chain_category_fv = FeatureView(
    name="supply_chain_category_features",
    entities=[supply_chain_item],
    ttl=timedelta(days=2),
    schema=[
        Field(name="dept_mean_sales",  dtype=Float32),
        Field(name="store_mean_sales", dtype=Float32),
        Field(name="cat_mean_sales",   dtype=Float32),
    ],
    online=True,
    source=supply_chain_source,
    tags={"domain": "supply_chain", "type": "aggregation"},
)

# ON-DEMAND FEATURE VIEW
# Computed at request time from other features — no historical storage
demand_input_source = RequestSource(
    name="demand_request",
    schema=[
        Field(name="current_sales", dtype=Float32),
    ],
)


@OnDemandFeatureView(
    sources=[supply_chain_rolling_fv, demand_input_source],
    schema=[
        Field(name="demand_z_score",        dtype=Float32),
        Field(name="demand_trend_7_28",     dtype=Float32),
        Field(name="demand_volatility_ratio", dtype=Float32),
    ],
)
def supply_chain_demand_score(
    inputs: pd.DataFrame,
) -> pd.DataFrame:
    """
    Computed on-demand signals:
    - demand_z_score: how many std deviations from 28d rolling mean
    - demand_trend_7_28: ratio of 7d mean to 28d mean (>1 = trending up)
    - demand_volatility_ratio: std/mean (coefficient of variation)
    """
    df = pd.DataFrame()

    mean_28 = inputs.get("rolling_mean_28", pd.Series([1.0] * len(inputs)))
    std_28  = inputs.get("rolling_std_28",  pd.Series([1.0] * len(inputs)))
    mean_7  = inputs.get("rolling_mean_7",  pd.Series([1.0] * len(inputs)))
    current = inputs.get("current_sales",   pd.Series([0.0] * len(inputs)))

    df["demand_z_score"]          = ((current - mean_28) / (std_28 + 1e-6)).astype("float32")
    df["demand_trend_7_28"]       = (mean_7 / (mean_28 + 1e-6)).astype("float32")
    df["demand_volatility_ratio"] = (std_28 / (mean_28 + 1e-6)).astype("float32")

    return df
